# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.roboo

# Dependencies
fabric_api_version=0.141.3+1.21.11
fabric_kotlin_version=1.13.8+kotlin.2.3.0

# MoulConfig - check https://github.com/NotEnoughUpdates/MoulConfig/tags for newer releases
moulconfig_version=4.3.0-beta
shadow_version=9.3.1
